/* View and controls; career rules live in engine.js, authored stories in cases.js. */
(() => {
  'use strict';
  const {Game,ORDERS}=globalThis.GoodLawyer;
  const game=new Game(globalThis.GOOD_LAWYER_CASES);
  const root=document.getElementById('good-lawyer'), $=s=>root.querySelector(s);
  const assetScript=document.currentScript,portrait=assetScript.dataset.portrait,videoSource=assetScript.dataset.video;
  const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
  const btn=(text,action,cls='secondary',disabled=false)=>`<button class="${cls}" data-action="${action}" ${disabled?'disabled':''}>${text}</button>`;
  const names={mark:'Марк Волков',irina:'Ирина Лебедева',contact:'Закрытый контакт'};
  const lines={alibi:'Алиби',procedure:'Ошибка в материалах',motive:'Иная версия событий'};
  const kinds={document:'Документ',witness:'Показания',physical:'Вещественное'};
  const questions={events:'Что вы видели лично?',time:'Когда это произошло?',detail:'Что подтверждает ваши слова?',conflict:'Как объяснить противоречие?',source:'Откуда вы это знаете?',certainty:'В чём вы не уверены?',review:'Сверить с новым документом',confirm:'Готовы повторить в суде?'};
  let ui={desk:'cases',phone:'chat',agent:'mark',device:'laptop',allTransactions:false},started=false,screen='menu',movieToken=0,finishMovie=null;
  function empty(title='Пока нет активного дела',body='Выберите дело и отправьте предложение клиенту на вкладке «Дела».') {return `<div class="empty"><span class="eyebrow">Ваша практика</span><h3>${title}</h3><p>${body}</p>${btn('Выбрать дело →','cases','primary')}</div>`;}
  function steps() {return `<div class="step-list" aria-label="Прогресс кампании">${Array.from({length:10},(_,i)=>`<span class="step-dot ${i+1<game.s.stage?'done':i+1===game.s.stage?'current':''}" title="Глава ${i+1}">${i+1<game.s.stage?'✓':i+1}</span>`).join('')}</div>`;}
  function tutorial() {
    const a=game.s.active,c=game.definition;if(!a||c.step!==1)return '';
    const text=!a.pending.length&&!a.done.length?'Начните с поручений: Ирина проверит документы, Марк — перемещения. Пока они работают, поговорите со свидетелем.':!a.questions.length?'Поручения в работе. На вкладке «Свидетель» выберите спокойный подход и задайте несколько вопросов.':!game.planOpen()?'Новые ответы и документы появятся после перехода дня. За день до суда откроется план защиты.':'План открыт. Включите проверенные документы, запись перемещений и протокол свидетеля. Поставьте документ перед показаниями.';
    return `<div class="hint"><strong>Первое дело / </strong>${text}</div>`;
  }
  function caseCard(c) {
    const r=game.requirement(c),accessible=game.eligible(c),s=game.s;
    return `<article class="case-card ${c.step===1?'tutorial':''}"><div><div class="case-id"><span class="eyebrow">Дело № ${safe(c.no)} / ${safe(c.district)}</span><span class="tag ${accessible?'green':''}">${accessible?'Доступно':'Высокий рейтинг'}</span></div><h3>${safe(c.title)}</h3><p>${safe(c.story)}</p><p class="goal">Клиент: ${safe(c.client)}<br>Задача: ${safe(c.objective)}</p><dl><div><dt>Гонорар за успех</dt><dd>${money(c.fee)}</dd></div><div><dt>Бюджет клиента</dt><dd>${money(c.budget)}</dd></div><div><dt>Подготовка</dt><dd>${c.ap} ОД · ${c.days} дней</dd></div><div><dt>Требования</dt><dd>Известность ${r.rep} · проф. ${r.professional}</dd></div></dl><div class="case-actions"><button class="primary" data-offer="${c.id}">Предложить защиту →</button><button class="text-button" data-probono="${c.id}">Помочь бесплатно · за свой счёт</button>${!accessible&&c.id===game.choices()[0]?.id?'<p class="small">Юридическая клиника направит это дело бесплатно даже при низкой известности.</p>':''}</div></div>${c.step===1?`<img class="case-portrait" src="${portrait}" alt="Адвокат готовится к первому делу">`:''}</article>`;
  }
  function casesView() {
    const s=game.s,a=s.active,c=game.definition;
    if(a)return `<div class="eyebrow">В работе / № ${safe(c.no)} / ${safe(c.type)}</div><h2 class="section-title">${safe(c.title)}</h2><p class="section-lead">${safe(c.story)}</p>${tutorial()}<div class="profile"><span class="eyebrow">Рассказ клиента · ${safe(c.client)}</span><h3>«Мне нужна ваша защита»</h3><p>${safe(c.objective)}</p><p style="margin-top:10px">${a.probono?'Бесплатная помощь: расходы на вас.':`Гонорар ${money(a.fee)}; при неудаче — 40%.`} Слушание: день ${a.deadline}. Запас на всё дело: ${a.apMax} ОД.</p></div>${tasksView()}<div class="choices">${btn('Открыть материалы дела →','dossier','primary')}${btn('Подготовить свидетеля →','witness')}${btn('Открыть поручения на телефоне →','phone')}</div>${steps()}`;
    if(s.campaignComplete)return `<div class="eyebrow">Кампания завершена / Северный берег</div><h2 class="section-title">Город знает ваше имя.</h2><p class="section-lead">Вы прошли десять глав и стали городским адвокатом. Выиграно ${s.wins} из ${s.completed.length} дел. Теперь можно проверить другой подход к завершённому делу: тренировка не изменит ресурсы карьеры.</p>${s.investigation?'<div class="hint warning">Расследование ещё продолжается. Дождитесь решения перед тренировкой.</div>':''}${steps()}<div class="section-head" style="margin-top:24px"><h3>Архив дел</h3><span class="tag">Тренировочные повторы</span></div><div class="materials">${s.completed.map(r=>`<article class="material"><div class="material-top"><h3>${safe(r.title)}</h3><span class="tag">${r.won?'Успех':'Неудача'} · ${r.score}%</span></div><button class="text-button" data-training="${r.id}" ${s.investigation?'disabled':''}>Переиграть без изменения карьеры →</button></article>`).join('')}</div><p class="section-lead" style="margin-top:22px">В этой версии доступна первая кампания. Продолжение, свободная игра и совместные дела описаны в плане развития.</p>`;
    return `<div class="eyebrow">Северный берег / глава ${s.stage} из 10</div><h2 class="section-title">${s.stage===1?'Первое дело. Ваше имя.':'Какое дело станет вашим?'}</h2><p class="section-lead">${s.stage===1?'В пригороде вас ещё почти не знают. Начните с небольшого дела: выслушайте клиента и соберите защиту.':'Выберите одно из двух дел. Второй путь останется для нового прохождения. Клиент ответит на предложение в почте.'}</p><div class="case-grid">${game.choices().map(caseCard).join('')}</div>${s.result?btn('Разбор предыдущего дела →','result','text-button'):''}${steps()}`;
  }
  function tasksView() {const a=game.s.active;if(!a?.pending.length)return '';return `<div class="section-head"><h3>Поручения в работе</h3><span class="tag">${a.pending.length}</span></div><div class="task-list">${a.pending.map(t=>`<div class="task"><div>${ORDERS[t.key].label}<small>${names[ORDERS[t.key].agent]} · ответ в день ${t.due}</small></div><span class="tag">${t.due-game.s.day} дн.</span></div>`).join('')}</div>`;}
  function materialCard(m,inPlan=false) {const a=game.s.active,selected=a.selection.includes(m.id);return `<article class="material ${m.risky?'risky':''} ${inPlan&&selected?'selected':''}"><div class="material-top"><h3>${safe(m.title)}</h3><span class="tag ${m.risky?'red':''}">${m.risky?'Спорный источник':kinds[m.kind]}</span></div><p>${safe(m.text)}</p><p><small>${safe(m.source)} · день ${m.day}</small></p>${inPlan?`<button class="${selected?'primary':'secondary'}" data-material="${m.id}" aria-pressed="${selected}">${selected?'✓ В плане · убрать':'+ Включить в план'}</button>`:''}</article>`;}
  function dossierView() {const a=game.s.active,c=game.definition;if(!a)return empty();return `<div class="eyebrow">Досье / ${safe(c.client)}</div><h2 class="section-title">Материалы дела</h2><p class="section-lead">${safe(c.objective)} В суд попадут только материалы плана. Не каждое найденное утверждение надёжно.</p>${tutorial()}${tasksView()}<div class="materials">${a.materials.map(m=>materialCard(m)).join('')}</div><section class="puzzle"><span class="eyebrow">Блокнот / необязательный анализ</span><h3>Найти несостыковку</h3><p>${safe(c.puzzle.prompt)}</p>${a.puzzleAttempted?`<div class="hint ${a.puzzleSolved?'':'warning'}">${a.puzzleSolved?'Верно. Заметка добавлена в досье.':'Ответ не подтвердился. Бонус не получен.'}<br>${safe(c.puzzle.explanation)}</div>`:`<div class="choices">${c.puzzle.options.map((o,i)=>`<button class="option" data-puzzle="${i}" aria-pressed="${a.puzzleChoice===i}" ${!game.canSpend(1)?'disabled':''}><span class="letter">${i+1}</span>${safe(o)}</button>`).join('')}</div><div class="choice-footer">${btn('Проверить · 1 ОД','solve','secondary',!game.canSpend(1)||a.puzzleChoice===null)}</div><p class="small" style="margin-top:12px">Одна попытка. Можно переключать вкладки: выбранный ответ сохранится.</p>`}</section>${btn('Перейти к плану защиты →','plan','text-button')}`;}
  function witnessView() {
    const a=game.s.active,c=game.definition;if(!a)return empty();const witnessMaterial=a.materials.find(m=>m.id==='witness');const trait={careful:'Внимательный. Лучше свободный рассказ, затем проверка фактов.',nervous:'Тревожный. Спокойные вопросы помогают; давление может обернуться жалобой.',stubborn:'Независимый. Навязывание версии приведёт к отказу выступать.'};
    return `<div class="eyebrow">Подготовка показаний</div><h2 class="section-title">Свидетель защиты</h2><p class="section-lead">Подход меняет надёжность показаний. Сначала можно поручить Марку собрать справку о человеке.</p><div class="profile"><span class="eyebrow">Приглашён защитой</span><h3>${safe(c.witness.name)}</h3><p>${a.profile?safe(trait[c.witness.trait]):'Справка ещё не получена. Вы знаете только рассказ клиента.'}</p>${a.profile===2?`<p style="margin-top:10px">${safe(c.witness.detail)}</p>`:''}</div>${witnessMaterial?.risky?`<div class="hint warning">${safe(witnessMaterial.text)}</div>`:''}${!a.approach?`<div class="approaches"><button class="approach" data-approach="free" ${!game.canSpend(1)?'disabled':''}><strong>Расскажите своими словами</strong><small>Точные воспоминания. Меньше контроля над версией.</small></button><button class="approach" data-approach="guided" ${!game.canSpend(1)?'disabled':''}><strong>Ответьте на мои вопросы</strong><small>Уточнить детали и сопоставить их с материалами.</small></button><button class="approach risky" data-approach="pressure" ${!game.canSpend(1)?'disabled':''}><strong>Согласуем удобные показания</strong><small>Теневой метод. Риск отказа или признания давления; внимание следствия растёт.</small></button></div>`:`<div class="section-head"><h3>Вопросы · ${a.questions.length} / 8</h3><span class="tag">По 1 ОД</span></div><div class="hint">Подход: ${a.approach==='free'?'свободный рассказ':a.approach==='guided'?'направляющие вопросы':'давление'}. Протокол обновляется после каждого нового ответа.</div><div class="question-grid">${Object.entries(questions).map(([key,label])=>`<button data-question="${key}" ${!game.canSpend(1)||a.questions.includes(key)||(key==='review'&&!a.done.includes('documents'))?'disabled':''}>${a.questions.includes(key)?'✓ ':''}${label}</button>`).join('')}</div>`}<div class="protocol"><div class="section-head"><h3>Протокол беседы</h3></div>${a.protocol.length?a.protocol.map(p=>`<article class="protocol-item"><strong>${safe(p.q)}</strong><p>${safe(p.a)}</p></article>`).join(''):'<p class="section-lead">Здесь сохранятся ответы и справки детектива.</p>'}</div><div class="hint warning" style="margin-top:20px">Свидетеля обвинения заранее опрашивать нельзя. Его показания рассматриваются только на заседании.</div>`;
  }
  function planView() {
    const a=game.s.active,c=game.definition;if(!a)return empty();
    if(!game.planOpen())return `<div class="eyebrow">Судебное заседание / день ${a.deadline}</div><h2 class="section-title">Сначала — подготовка.</h2><p class="section-lead">План откроется в день ${a.deadline-1}, за сутки до суда, или раньше при нуле ОД. До этого собирайте материалы и готовьте свидетеля.</p>${tasksView()}${btn('Открыть досье →','dossier','primary')}${c.step>=4&&!a.postponed?`<div class="hint" style="margin-top:20px">Один перенос: +2 дня, −20% гонорара и −4 балла к итогу. ОД не восстанавливаются.<br>${btn('Перенести заседание','postpone','text-button')}</div>`:''}`;
    const assessment=game.assessment(),plan=game.plan();
    return `<div class="eyebrow">Подготовка к заседанию</div><h2 class="section-title">Ваша линия защиты</h2><p class="section-lead">Судья ${safe(c.judge.name)}. ${safe(c.judge.hint)} ${a.pending.length?'Часть поручений ещё в работе: если пойти в суд сейчас, их материалы не будут учтены.':''}</p><div class="plan-lines">${Object.entries(lines).map(([key,label])=>`<button data-line="${key}" aria-pressed="${a.line===key}">${label}</button>`).join('')}</div>${!a.line?'<div class="hint warning">Линия не выбрана: по умолчанию адвокат заявит алиби.</div>':''}<div class="section-head"><h3>Порядок выступления</h3><span class="tag">${plan.length} / 4 материала</span></div>${!a.manualPlan?'<div class="hint warning">План не составлен. Суд получит первые четыре материала в порядке поступления — включая непроверенные. Выберите карточки ниже, чтобы собрать свою защиту.</div>':''}<div class="plan-order">${plan.length?plan.map((id,i)=>{const m=a.materials.find(m=>m.id===id);return `<div class="plan-row"><span>0${i+1}</span><span>${safe(m.title)}</span>${a.manualPlan?`<button data-up="${id}" aria-label="Поднять ${safe(m.title)}" ${i===0?'disabled':''}>↑</button><button data-down="${id}" aria-label="Опустить ${safe(m.title)}" ${i===plan.length-1?'disabled':''}>↓</button>`:''}</div>`;}).join(''):'<p class="section-lead">Вы пока не выбрали ни одного материала.</p>'}</div><div class="plan-estimate"><div><span class="eyebrow" style="color:#c7d2b8">Оценка плана</span><p>Для успеха нужно ${c.target}.<br>Ответ в суде и проверка спорных материалов изменят итог.</p></div><strong>${assessment.score}<span style="font:12px Arial"> / 100</span></strong></div><div class="materials">${a.materials.map(m=>materialCard(m,true)).join('')}</div>${a.postponed?'<p class="section-lead" style="margin-top:20px">Перенос уже использован. Итог защиты получит штраф 4 балла.</p>':c.step>=4?`<div class="hint" style="margin-top:20px">Перенос: +2 дня, −20% гонорара, −4 балла к итогу. Один раз за дело.<br>${btn('Перенести заседание','postpone','text-button')}</div>`:''}`;
  }
  function careerView() {
    const s=game.s,status=s.campaignComplete?'Городской адвокат':'Начинающий адвокат';
    return `<div class="eyebrow">Карьера / ${status}</div><h2 class="section-title">Имя, которое вы строите.</h2><p class="section-lead">Известность привлекает клиентов, профессионализм подтверждает опыт. Теневая репутация отражает методы; внимание следствия показывает текущий риск.</p><label class="eyebrow" for="name-input">Ваше имя</label><form id="name-form" class="name-form"><input id="name-input" maxlength="40" value="${safe(s.name)}" required aria-label="Имя адвоката"><button class="secondary" type="submit">Сохранить</button></form><div class="career-stats"><div><b>${s.wins}/${s.completed.length}</b><span>Выиграно дел</span></div><div><b>${s.shadow}</b><span>Теневая репутация</span></div><div><b>${s.suit&&s.wear>0?12:0}</b><span>Имидж</span></div></div><div class="section-head"><h3>Районы Новореченска</h3></div><div class="map">${['Пригород','Старый порт','Речной район','Деловой квартал','Холм'].map((label,i)=>`<div class="district ${s.stage>=1+i*2?'open':''}">${label}<br><small>Глава ${1+i*2}</small></div>`).join('')}</div><div class="career-grid"><article class="career-card"><h3>Свой офис</h3><p>Место для помощника. Открытие — 30 000 ₽; аренда дороже на 4 000 ₽ в неделю. Доступен после двух дел.</p>${btn(s.office?'Офис открыт':'Открыть офис','buy-office','secondary',!!s.office||s.completed.length<2||s.training)}</article><article class="career-card"><h3>Помощник аналитика</h3><p>Два одновременных поручения Ирине, каждое на день быстрее. Наём — 18 000 ₽; зарплата — 5 000 ₽ в неделю.</p>${btn(s.assistant?'В штате':'Нанять помощника','buy-assistant','secondary',s.assistant||!s.office||s.training)}</article><article class="career-card"><h3>Деловой костюм</h3><p>12 000 ₽. Имидж +12 и +2 балла в суде. Состояние уменьшается на 15% за дело; изношенный костюм не даёт бонуса.</p>${s.suit?`<p>Состояние: ${s.wear}%</p>${btn('Уход за костюмом · 3 000 ₽','buy-repair','secondary',s.wear===100||s.training)}`:btn('Приобрести костюм','buy-suit','secondary',s.training)}</article><article class="career-card"><h3>Содержание практики</h3><p>Следующее списание: день ${nextBill()}. Всего ${money(game.weeklyCost())} за семь игровых дней. Расходы видны в банке.</p>${btn('Открыть банк →','bank','secondary')}</article></div><div class="hint">В этой кампании вы ведёте одно дело. Персонал расширяет очередь поручений. Другие города, несколько дел одновременно и коллегии — следующие этапы.</div>`;
  }
  function newsView() {return `<div class="eyebrow">Городская хроника</div><h2 class="section-title">Что происходит за окном.</h2>${game.s.news.map(n=>`<article class="news"><small>ДЕНЬ ${n.day} / ВАША ПРАКТИКА</small><h3>${safe(n.title)}</h3><p>${safe(n.body)}</p></article>`).join('')}<article class="news"><small>ГОРОД / РАССЛЕДОВАНИЕ</small><h3>Чей берег — Северный?</h3><p>Название холдинга всё чаще появляется в спорах пригорода и порта. Отдельные дела могут оказаться частями одной истории.</p></article><article class="news"><small>ОБЩЕСТВО / ЮРИДИЧЕСКАЯ КЛИНИКА</small><h3>Помощь тем, кто не может заплатить</h3><p>Бесплатная защита повышает известность и снижает внимание властей. Все расходы адвокат оплачивает сам. Собранные улики действующего расследования сохраняются.</p></article>`;}
  function mailView() {return `<div class="eyebrow">Входящие / ${game.s.mail.length} писем</div><h2 class="section-title">Почта практики</h2>${game.s.active?btn('Открыть активное досье →','dossier','primary'):btn('Выбрать следующее дело →','cases','primary')}${game.s.mail.map(m=>`<article class="mail"><small>${safe(m.from)} / ДЕНЬ ${m.day}</small><h3>${safe(m.title)}</h3><p>${safe(m.body)}</p></article>`).join('')}`;}
  function resultView() {
    const r=game.s.result;if(!r)return empty('Результатов пока нет','Первый разбор появится после заседания.');
    return `<div class="eyebrow">${r.training?'Тренировочный ':''}Итог заседания</div><div class="result-hero ${r.won?'':'fail'}"><div><h2 class="section-title">${r.late?'Слушание пропущено.':r.won?'Защита сработала.':'Доводов не хватило.'}</h2><p class="section-lead" style="margin:0">${safe(r.title)}</p></div><div><span class="result-score">${r.score}%</span><small>Цель: ${r.target}%</small></div></div>${r.late?'<div class="hint warning">Дело проиграно из-за пропуска заседания независимо от качества подготовки.</div>':''}<div class="section-head"><h3>Из чего сложился результат</h3></div>${r.rows.map(row=>`<div class="result-row"><span>${safe(row.label)}</span><b class="${row.value<0?'negative':''}">${row.value>0?'+':''}${row.value}</b></div>`).join('')}<div class="result-finance">Гонорар: <strong>${money(r.fee)}</strong><br>Известность +${r.repGain} · профессионализм +${r.professionalGain}<br>Личные вложения: ${money(r.invested)}<br>Возвращено клиенту: ${money(r.returned)}${r.training?'<br><strong>Все изменения относятся только к тренировке. Карьера сохранена.</strong>':''}</div>${r.training?btn('Вернуться в карьеру →','leave-training','primary'):btn(game.s.campaignComplete?'Открыть итоги кампании →':'Следующая глава →','cases','primary')}`;
  }
  function nextBill(){return 1+7*(Math.floor((game.s.day-1)/7)+1);}
  function phoneView() {
    const s=game.s,a=s.active;
    if(ui.phone==='bank')return `<div class="bank"><span class="eyebrow">Личный расчётный счёт</span><div class="balance">${money(s.money)}</div><div class="bank-card">КАПИТАЛ / ЧАСТНАЯ ПРАКТИКА<span>•••• 0418 &nbsp; Новореченский банк</span></div>${a?`<div class="budget-card"><span class="eyebrow">Бюджет клиента / отдельно</span><b>${money(a.budget)}</b><p>Получено ${money(a.initialBudget)}. Остаток после суда вернётся клиенту. Личные вложения: ${money(a.invested)}.</p><label class="funding"><input id="personal-funding" type="checkbox" ${a.personalFunding?'checked':''}><span>Разрешить оплату сверх бюджета с личного счёта</span></label><p>Перед поручением показано, сколько спишется с каждого счёта.</p></div>`:''}<div class="bill-info">Расходы за неделю: ${money(game.weeklyCost())}<br>Аренда ${money(s.office?7000:3000)} · персонал ${money(s.assistant?5000:0)}<br>Следующее списание: день ${nextBill()}${s.debt?`<br><strong>Задолженность: ${money(s.debt)}</strong><br>${btn('Погасить долг','debt','text-button',!s.money)}`:''}</div><div class="section-head"><span class="eyebrow">История операций</span></div>${(ui.allTransactions?s.transactions:s.transactions.slice(0,8)).map(t=>`<div class="transaction"><div>${safe(t.name)}<small>День ${t.day} · ${t.account==='personal'?'Личный счёт':'Бюджет клиента'}</small></div><span class="${t.amount<0?'out':''}">${t.amount>0?'+':''}${money(t.amount)}</span></div>`).join('')}${s.transactions.length>8?btn(ui.allTransactions?'Свернуть историю':'Все операции','transactions','transactions-toggle'):''}</div>`;
    const agent=ui.agent,contacts=['mark','irina',...(s.stage>=3||s.training?['contact']:[])],busy=a?.pending.filter(t=>ORDERS[t.key].agent===agent).length||0;
    const chat=s.chats[agent].slice(-3);
    const orders=Object.entries(ORDERS).filter(([,o])=>o.agent===agent);
    return `<div class="contact"><div class="avatar">${agent==='mark'?'МВ':agent==='irina'?'ИЛ':'••'}</div><div><select id="agent-select" aria-label="Исполнитель">${contacts.map(k=>`<option value="${k}" ${agent===k?'selected':''}>${names[k]}</option>`).join('')}</select><small>${busy?`В работе: ${busy}`:agent==='mark'?'Частный детектив':agent==='irina'?'Аналитик'+(s.assistant?' + помощник':''):'Теневые поручения'}</small></div></div><div class="chat">${chat.length?chat.map(m=>`<div class="bubble ${m.mine?'mine':''}">${safe(m.text)}<small>${m.mine?'Вы':'Получено'} · день ${m.day}</small></div>`).join(''):`<div class="bubble">${a?'Готов принять поручение. Результаты появятся после перехода дня.':'Сначала заключите договор с клиентом. Затем сможем начать работу.'}<small>${names[agent]}</small></div>`}</div><div class="orders"><div class="eyebrow">Поручения по делу ${a?'№ '+safe(game.definition.no):''}</div>${orders.map(([key,o])=>{const q=game.quote(key),blocked=game.orderBlock(key);return `<button class="order ${o.heat?'illegal':''}" data-order="${key}" ${blocked?'disabled':''}><strong>${o.label}</strong><small>${money(o.cost)} · ${o.ap} ОД · ${q?q.days:o.days} дн.</small>${q?`<small>Клиент ${money(q.client)} · вы ${money(q.personal)}</small>`:''}${o.heat?'<small class="risk">Незаконно · риск расследования</small>':''}${blocked?`<small>${safe(blocked)}</small>`:''}</button>`;}).join('')}</div><p class="phone-tip">${a?.ap===0?'ОД закончились. Дождитесь запущенных поручений, составьте план и идите в суд.':'Поручения идут параллельно вашей подготовке. У каждого исполнителя своя очередь.'}${a?`<br>${btn('Проверить бюджет →','bank','text-button')}`:''}</p>`;
  }
  function render() {
    const s=game.s,a=s.active,c=game.definition;
    root.dataset.device=ui.device;
    $('#chapter-label').textContent=s.training?'Тренировочное дело':s.campaignComplete?'Северный берег · кампания завершена':`Северный берег · глава ${s.stage} / 10`;
    $('#day-label').textContent='День '+s.day;$('#district-label').textContent=c?.district||'Новореченск';$('#lawyer-name').textContent=s.name;
    for(const key of ['rep','professional','heat']){$('#'+key).textContent=s[key];$('#'+key+'-bar').style.width=s[key]+'%';}
    $('#mail-badge').textContent=s.unread;$('#mail-badge').hidden=!s.unread;$('#phone-badge').textContent=a?.pending.length?'· '+a.pending.length:'';
    $('#training-banner').hidden=!s.training;
    for(const attr of ['desk','phone','device'])root.querySelectorAll('button[data-'+attr+']').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset[attr]===ui[attr])));
    const strip=$('#case-strip');strip.hidden=!a;
    if(a)strip.innerHTML=`<strong>№ ${safe(c.no)} · ${safe(c.title)}</strong><div><span>Суд: день ${a.deadline}${s.day===a.deadline?' · сегодня':''}</span><span class="ap ${!a.ap?'empty':''}"><b>${a.ap}</b> / ${a.apMax} ОД</span></div>`;
    const views={cases:casesView,dossier:dossierView,witness:witnessView,plan:planView,career:careerView,news:newsView,mail:mailView,result:resultView};
    $('#desktop-content').innerHTML=(views[ui.desk]||casesView)();
    $('#phone-content').innerHTML=phoneView();$('#phone-title').textContent=ui.phone==='bank'?'Капитал':'Контакты';
    $('#court-button').disabled=!a||!game.planOpen()||!!s.ending;$('#court-button').textContent='В суд →';
    $('#day-button').disabled=!!s.ending||(!a&&!s.investigation);$('#day-button').textContent=a&&s.day>=a.deadline?'Завершить день · пропуск суда':'Следующий день →';
    $('#footer-label').textContent=a?s.day>=a.deadline?'Заседание сегодня. Следующий день означает поражение.':!a.ap?'ОД закончились; поручения продолжают выполняться.':`Подготовка до дня ${a.deadline}. ОД не восстанавливаются.`:'Время идёт только по вашей команде.';
    const p=s.investigation;$('#investigation').hidden=!p;
    if(p)$('#investigation').innerHTML=`<h3>Дело против вас</h3><p>Сила обвинения ${p.evidence}/100. Решение в день ${p.due}. От 50 — штраф; от 75 — тюрьма. Снижение внимания не убирает собранные улики.</p>${p.defended?'<p>Независимая защита уже учтена.</p>':btn('Нанять защитника · 25 000 ₽ · 1 день','defend','secondary',s.money<25000)}`;
    $('#notice').textContent=s.notice;
    if(s.ending&&screen==='game')showPrison();
  }
  function clearOverlay() {movieToken++;finishMovie=null;const v=$('#court-video');if(v)v.pause();$('#overlay').hidden=true;$('#overlay').innerHTML='';$('#workspace').inert=false;}
  function showMenu() {clearOverlay();game.cancelCourt();screen='menu';$('#menu').hidden=false;$('#workspace').hidden=true;$('[data-action="continue"]').hidden=!started||(!!game.s.ending&&!game.s.training);$('#rules').hidden=true;$('[data-action="rules"]').setAttribute('aria-expanded','false');window.scrollTo(0,0);$('[data-action="new-game"]').focus({preventScroll:true});}
  function enterGame() {screen='game';$('#menu').hidden=true;$('#workspace').hidden=false;render();window.scrollTo(0,0);$('[data-action="menu"]').focus({preventScroll:true});}
  function newGame() {clearOverlay();game.reset();ui={desk:'cases',phone:'chat',agent:'mark',device:'laptop',allTransactions:false};started=true;enterGame();}
  function openOverlay(html) {$('#overlay').innerHTML=html;$('#overlay').hidden=false;$('#workspace').inert=true;$('#overlay').querySelector('button')?.focus();}
  function showCourt() {
    if(!game.beginCourt().ok){render();return;}
    const c=game.definition,s=game.s,selected=game.plan().map(id=>safe(s.active.materials.find(m=>m.id===id).title)).join(' → ')||'Материалы не выбраны';
    openOverlay(`<section class="dialog" role="dialog" aria-modal="true" aria-labelledby="court-title"><div class="eyebrow">Заседание / ${safe(c.judge.name)}</div><h2 id="court-title">${s.rep>=45?safe(s.name)+', ваша позиция.':'Господин адвокат, ваша позиция.'}</h2><p>${selected}</p><p>${safe(c.court.prompt)}</p><div class="choices">${c.court.options.map((o,i)=>`<button class="option" data-court-answer="${i}"><span class="letter">0${i+1}</span>${safe(o)}</button>`).join('')}</div>${btn('Вернуться к подготовке','cancel-court','secondary')}</section>`);
  }
  function cinema() {
    const c=game.definition,token=++movieToken;
    openOverlay(`<section class="dialog cinema" role="dialog" aria-modal="true" aria-labelledby="film-title"><video id="court-video" playsinline preload="auto" poster="${portrait}" src="${videoSource}" aria-label="Судебная сцена продолжительностью восемь секунд"></video><div><div class="eyebrow">Ключевой момент / 8 секунд</div><h2 id="film-title">Последнее слово защиты.</h2><p>${safe(c.title)}<br>Суд рассматривает ваши материалы и ответ.</p><div class="film-progress"><span id="film-bar"></span></div><div id="film-time" class="film-time">00:00 / 00:08</div><div class="dialog-actions">${btn('К результату →','skip','secondary')}${btn('В меню','menu','secondary')}<button class="secondary" data-action="play" hidden>Включить видео</button></div></div></section>`);
    const v=$('#court-video');
    finishMovie=()=>{if(token!==movieToken)return;clearOverlay();game.finishCourt();ui.desk='result';ui.device='laptop';render();$('#desktop-content').scrollIntoView({block:'start'});};
    v.addEventListener('ended',()=>{if(token===movieToken)finishMovie?.();});
    v.addEventListener('timeupdate',()=>{if(token!==movieToken||$('#court-video')!==v)return;$('#film-bar').style.width=Math.min(100,v.currentTime/8*100)+'%';$('#film-time').textContent='00:'+String(Math.min(8,Math.floor(v.currentTime))).padStart(2,'0')+' / 00:08';if(v.currentTime>=8)finishMovie?.();});
    v.addEventListener('error',()=>{if(token===movieToken&&$('#film-time'))$('#film-time').textContent='Видео недоступно. Нажмите «К результату».';});
    v.play().catch(()=>{if(token===movieToken&&$('[data-action="play"]'))$('[data-action="play"]').hidden=false;});
  }
  function showPrison(){if($('#prison-title'))return;openOverlay(`<section class="dialog prison" role="dialog" aria-modal="true" aria-labelledby="prison-title"><div class="eyebrow">Дело против адвоката / финал</div><h2 id="prison-title">Теперь вы —<br>подзащитный.</h2><p>Следствие доказало систематическое вмешательство в показания. Суд назначил тюремное заключение. Практика закрыта.</p><p>День ${game.s.day} · завершено дел: ${game.s.completed.length} · известность: ${game.s.rep}</p><div class="dialog-actions">${game.s.training?btn('Вернуться в карьеру','leave-training','primary'):btn('Новая игра','new-game','primary')}${btn('Главное меню','menu','secondary')}</div></section>`);}
  function navigate(desk){ui.desk=desk;ui.device='laptop';if(desk==='mail')game.s.unread=0;}
  root.addEventListener('click',e=>{
    const b=e.target.closest('button');if(!b||b.disabled||!root.contains(b))return;const action=b.dataset.action;
    if(action==='new-game'){newGame();return;}if(action==='menu'){showMenu();return;}
    if(action==='continue'){if(started&&(!game.s.ending||game.s.training))enterGame();return;}
    if(action==='rules'){const rules=$('#rules');rules.hidden=!rules.hidden;b.setAttribute('aria-expanded',String(!rules.hidden));return;}
    if(action==='leave-training'){clearOverlay();game.leaveTraining();ui.desk='cases';ui.device='laptop';enterGame();return;}
    if(screen!=='game')return;
    if(!$('#overlay').hidden){
      if(b.dataset.courtAnswer!==undefined&&game.chooseCourt(Number(b.dataset.courtAnswer)))cinema();
      else if(action==='skip')finishMovie?.();
      else if(action==='play')$('#court-video')?.play().then(()=>{b.hidden=true;}).catch(()=>{});
      else if(action==='cancel-court'){clearOverlay();game.cancelCourt();render();}
      return;
    }
    const previous=game.s.result;
    if(b.dataset.desk)navigate(b.dataset.desk);
    else if(b.dataset.phone)ui.phone=b.dataset.phone;
    else if(b.dataset.device)ui.device=b.dataset.device;
    else if(b.dataset.offer){game.offer(b.dataset.offer);navigate('mail');}
    else if(b.dataset.probono){game.offer(b.dataset.probono,true);navigate('mail');}
    else if(b.dataset.order)game.order(b.dataset.order);
    else if(b.dataset.approach)game.chooseApproach(b.dataset.approach);
    else if(b.dataset.question)game.question(b.dataset.question);
    else if(b.dataset.puzzle!==undefined)game.puzzleSelect(Number(b.dataset.puzzle));
    else if(b.dataset.material)game.toggleMaterial(b.dataset.material);
    else if(b.dataset.line)game.setLine(b.dataset.line);
    else if(b.dataset.up)game.move(b.dataset.up,-1);
    else if(b.dataset.down)game.move(b.dataset.down,1);
    else if(b.dataset.training){if(game.training(b.dataset.training).ok){ui.desk='dossier';ui.agent='mark';ui.phone='chat';}}
    else if(['cases','dossier','witness','plan','career','result'].includes(action))navigate(action);
    else if(action==='phone'){ui.device='phone';ui.phone='chat';}
    else if(action==='bank'){ui.device='phone';ui.phone='bank';}
    else if(action==='day')game.nextDay();
    else if(action==='solve')game.solvePuzzle();
    else if(action==='postpone')game.postpone();
    else if(action==='defend')game.defend();
    else if(action==='court'){showCourt();return;}
    else if(action?.startsWith('buy-'))game.buy(action.slice(4));
    else if(action==='debt')game.payDebt();
    else if(action==='transactions')ui.allTransactions=!ui.allTransactions;
    if(game.s.result&&game.s.result!==previous){ui.desk='result';ui.device='laptop';}
    render();
    if(b.dataset.device||action==='phone'||action==='bank')window.scrollTo(0,0);
  });
  root.addEventListener('change',e=>{if(e.target.id==='agent-select'){ui.agent=e.target.value;render();$('#agent-select').focus();}else if(e.target.id==='personal-funding'&&game.s.active){game.s.active.personalFunding=e.target.checked;game.say(e.target.checked?'Личные вложения разрешены. Перед поручением показана сумма.':'Оплата ограничена бюджетом клиента.');render();$('#personal-funding').focus();}});
  root.addEventListener('submit',e=>{if(e.target.id==='name-form'){e.preventDefault();const value=$('#name-input').value.trim();if(value){game.s.name=value.slice(0,40);game.say('Имя адвоката обновлено.');render();}}});
  document.addEventListener('keydown',e=>{
    if(e.key==='Escape'&&screen==='game'){e.preventDefault();if(!$('#overlay').hidden&&game.s.active?.phase==='court'){clearOverlay();game.cancelCourt();render();}else if(!game.s.ending)showMenu();return;}
    if(e.key==='Tab'&&!$('#overlay').hidden){const nodes=[...$('#overlay').querySelectorAll('button:not([hidden]):not(:disabled)')],first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}
  });
  if('scrollRestoration'in history)history.scrollRestoration='manual';
  window.addEventListener('pageshow',e=>{if(e.persisted){game.reset();started=false;ui={desk:'cases',phone:'chat',agent:'mark',device:'laptop',allTransactions:false};showMenu();}});
  showMenu();
})();
